# Generated by Django 6.0.1 on 2026-01-13 03:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='e.g. #Niv-Bishbc', max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(help_text='Client Name (Top Left)', max_length=200)),
                ('invoice_to', models.CharField(help_text='To: (Top Right)', max_length=200)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='PAID', max_length=10)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('passport_number', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='core.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='RAMADAN UMRAH FULL PACKAGE', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quantity_unit', models.CharField(default='PERSONS', help_text='e.g. PERSONS, TICKETS', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=15)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.receipt')),
            ],
        ),
    ]
